name: Bug Report
description: Report a bug to help us improve
title: '[BUG] '
labels: ['bug']
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you?
      placeholder: email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you saw
    validations:
      required: true
