name: Idea or Feature
description: Initial your idea or features
labels: ['feature']
projects: ['Thammasok/.workspace-bussiness']
assignees: []
body:
  - type: markdown
    attributes:
      value: Do you have any ideas? Please provide us with some ideas for new features or bug fixes.

  - type: textarea
    id: issue-detail
    attributes:
      label: Add a description
      description: Please provide a detailed description of your idea or feature request. The more information you can provide, the better!
      placeholder: ex. I want to add support for dark mode because it would be easier on my eyes when I'm working at night.
    validations:
      required: true
