name: Task
description: Create a sub task
body:
  - type: dropdown
    id: task-assign-team
    attributes:
      label: Task Type
      options:
        - ux-ui-design
        - test-design
        - refinement
        - task
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: Detail
    validations:
      required: true
